"""fix field name

Revision ID: 8bacff9a0333
Revises: 2720807ec3d2
Create Date: 2026-05-09 16:14:40.778104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bacff9a0333'
down_revision = '2720807ec3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('leave_requests_leave_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'leave_types', ['leave_type_id'], ['id'])
        batch_op.drop_column('leave_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leave_requests_leave_id_fkey'), 'leave_types', ['leave_id'], ['id'])
        batch_op.drop_column('leave_type_id')

    # ### end Alembic commands ###
